version: '3.8'
services:
 webcontext:
  build:
   context: ./WebContext
   dockerfile: Dockerfile
  ports:
  - "777:80"
  depends_on:
  - database
  networks:
  - network

 database:
  build:
   context: ./Database
   dockerfile: Dockerfile
  ports:
  - "5433:5432"
  networks:
  - network

networks:
 network:
  driver: bridge
